---
title: "Covid_Temp"
author: "Joon Kang"
date: "10/22/2020"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(stringr)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

df_Polar <- as_tibble(read.csv("./data/covid_19_clean_complete.csv"))%>%
  filter(Lat < -66.5 || Lat > 66.5)%>%
  select(Province.State,Country.Region,Lat,Long,Date,Confirmed)
  
df_Polar

df_Tropic <- as_tibble(read.csv("./data/covid_19_clean_complete.csv"))%>%
  filter(between(Lat,-23.5,23.5))%>%
  select(Province.State,Country.Region,Lat,Long,Date,Confirmed)
  
df_Tropic

df_Temperate <- as_tibble(read.csv("./data/covid_19_clean_complete.csv"))%>%
  filter(between(Lat,22.5,66.5) || between(Lat,-22.5,-66.5))%>%
  select(Province.State,Country.Region,Lat,Long,Date,Confirmed)
  
df_Temperate

```

```{r}
df_byzone <-
  df_Tropic%>%
    mutate(By_Latitude = case_when(
    between(Long, -180,-150) ~ "-180~-150",
    between(Long, -150, -120) ~ "-150~-120",
    between(Long, -120, -90) ~ "-120~-90",
    between(Long, -90, -60) ~ "-90~-60",
    between(Long, -60, -30) ~ "-60~-30",
    between(Long, -30, 0) ~ "-30~0",
    between(Long, 0, 30) ~ "0~30",
    between(Long, 30, 60) ~ "30~60",
    between(Long, 60, 90) ~ "60~90",
    between(Long, 90, 120) ~ "90~120",
    between(Long, 120, 150) ~ "120~150",
    between(Long, 150, 180) ~ "150~180",
    TRUE ~ NA_character_
  ),Date = as.Date(Date))

df_byzonef <- 
  df_byzone %>%
    group_by(Date)%>%
      select(Country.Region,Confirmed,By_Latitude)

df_byzonef

df_byzoneff <- 
  df_byzonef%>%
    group_by(Date,By_Latitude)%>%
        mutate(Cumulative_Cases = sum(Confirmed))
        

df_byzoneff

ggplot(df_byzoneff,aes(x=Date, y=Cumulative_Cases)) +
      theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))+scale_x_date()+
      geom_line(aes(color = By_Latitude))+
      ggtitle("Tropic Region Cumulative Cases by Latitude")
      
      
```
```{r}
df_byzone <-
  df_Temperate%>%
    mutate(By_Latitude = case_when(
    between(Long, -180,-150) ~ "-180~-150",
    between(Long, -150, -120) ~ "-150~-120",
    between(Long, -120, -90) ~ "-120~-90",
    between(Long, -90, -60) ~ "-90~-60",
    between(Long, -60, -30) ~ "-60~-30",
    between(Long, -30, 0) ~ "-30~0",
    between(Long, 0, 30) ~ "0~30",
    between(Long, 30, 60) ~ "30~60",
    between(Long, 60, 90) ~ "60~90",
    between(Long, 90, 120) ~ "90~120",
    between(Long, 120, 150) ~ "120~150",
    between(Long, 150, 180) ~ "150~180",
    TRUE ~ NA_character_
  ),Date = as.Date(Date))

df_byzonef <- 
  df_byzone %>%
    group_by(Date)%>%
      select(Country.Region,Confirmed,By_Latitude)

df_byzonef

df_byzoneff <- 
  df_byzonef%>%
    group_by(Date,By_Latitude)%>%
        mutate(Cumulative_Cases = sum(Confirmed))
        

df_byzoneff

ggplot(df_byzoneff,aes(x=Date, y=Cumulative_Cases)) +
      theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))+scale_x_date()+
      geom_line(aes(color = By_Latitude))+ggtitle("Temperate Region Cumulative Cases by Latitude")
```


